//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class achievement_criteria_requirement
    {
        public decimal criteria_id { get; set; }
        public byte type { get; set; }
        public decimal value1 { get; set; }
        public decimal value2 { get; set; }
    }
}
