//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_equip_template
    {
        public decimal entry { get; set; }
        public decimal equipentry1 { get; set; }
        public decimal equipentry2 { get; set; }
        public decimal equipentry3 { get; set; }
    }
}
