//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_template_classlevelstats
    {
        public short Level { get; set; }
        public short Class { get; set; }
        public decimal BaseHealthExp0 { get; set; }
        public decimal BaseMana { get; set; }
        public float BaseDamageExp0 { get; set; }
        public float BaseMeleeAttackPower { get; set; }
        public float BaseRangedAttackPower { get; set; }
        public decimal BaseArmor { get; set; }
    }
}
