//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_conditional_spawn
    {
        public long Guid { get; set; }
        public decimal EntryAlliance { get; set; }
        public decimal EntryHorde { get; set; }
        public string Comments { get; set; }
    }
}
