//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_linking_template
    {
        public decimal entry { get; set; }
        public int map { get; set; }
        public decimal master_entry { get; set; }
        public decimal flag { get; set; }
        public decimal search_range { get; set; }
    }
}
