//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_cooldowns
    {
        public decimal Entry { get; set; }
        public long SpellId { get; set; }
        public long CooldownMin { get; set; }
        public long CooldownMax { get; set; }
    }
}
