//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature
    {
        public long guid { get; set; }
        public decimal id { get; set; }
        public int map { get; set; }
        public decimal modelid { get; set; }
        public decimal equipment_id { get; set; }
        public float position_x { get; set; }
        public float position_y { get; set; }
        public float position_z { get; set; }
        public float orientation { get; set; }
        public long spawntimesecsmin { get; set; }
        public long spawntimesecsmax { get; set; }
        public float spawndist { get; set; }
        public decimal currentwaypoint { get; set; }
        public long curhealth { get; set; }
        public long curmana { get; set; }
        public byte DeathState { get; set; }
        public byte MovementType { get; set; }
    }
}
