//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_template
    {
        public decimal Entry { get; set; }
        public string Name { get; set; }
        public string SubName { get; set; }
        public byte MinLevel { get; set; }
        public byte MaxLevel { get; set; }
        public decimal ModelId1 { get; set; }
        public decimal ModelId2 { get; set; }
        public decimal ModelId3 { get; set; }
        public decimal ModelId4 { get; set; }
        public int Faction { get; set; }
        public float Scale { get; set; }
        public short Family { get; set; }
        public byte CreatureType { get; set; }
        public byte InhabitType { get; set; }
        public byte RegenerateStats { get; set; }
        public byte RacialLeader { get; set; }
        public long NpcFlags { get; set; }
        public long UnitFlags { get; set; }
        public long DynamicFlags { get; set; }
        public long ExtraFlags { get; set; }
        public long CreatureTypeFlags { get; set; }
        public float SpeedWalk { get; set; }
        public float SpeedRun { get; set; }
        public long Detection { get; set; }
        public long CallForHelp { get; set; }
        public long Pursuit { get; set; }
        public long Leash { get; set; }
        public long Timeout { get; set; }
        public byte UnitClass { get; set; }
        public byte Rank { get; set; }
        public float HealthMultiplier { get; set; }
        public float PowerMultiplier { get; set; }
        public float DamageMultiplier { get; set; }
        public float DamageVariance { get; set; }
        public float ArmorMultiplier { get; set; }
        public float ExperienceMultiplier { get; set; }
        public long MinLevelHealth { get; set; }
        public long MaxLevelHealth { get; set; }
        public long MinLevelMana { get; set; }
        public long MaxLevelMana { get; set; }
        public float MinMeleeDmg { get; set; }
        public float MaxMeleeDmg { get; set; }
        public float MinRangedDmg { get; set; }
        public float MaxRangedDmg { get; set; }
        public decimal Armor { get; set; }
        public long MeleeAttackPower { get; set; }
        public int RangedAttackPower { get; set; }
        public long MeleeBaseAttackTime { get; set; }
        public long RangedBaseAttackTime { get; set; }
        public short DamageSchool { get; set; }
        public decimal MinLootGold { get; set; }
        public decimal MaxLootGold { get; set; }
        public decimal LootId { get; set; }
        public decimal PickpocketLootId { get; set; }
        public decimal SkinningLootId { get; set; }
        public long KillCredit1 { get; set; }
        public long KillCredit2 { get; set; }
        public long MechanicImmuneMask { get; set; }
        public long SchoolImmuneMask { get; set; }
        public short ResistanceHoly { get; set; }
        public short ResistanceFire { get; set; }
        public short ResistanceNature { get; set; }
        public short ResistanceFrost { get; set; }
        public short ResistanceShadow { get; set; }
        public short ResistanceArcane { get; set; }
        public decimal PetSpellDataId { get; set; }
        public byte MovementType { get; set; }
        public short TrainerType { get; set; }
        public decimal TrainerSpell { get; set; }
        public byte TrainerClass { get; set; }
        public byte TrainerRace { get; set; }
        public decimal TrainerTemplateId { get; set; }
        public decimal VendorTemplateId { get; set; }
        public decimal GossipMenuId { get; set; }
        public short visibilityDistanceType { get; set; }
        public decimal EquipmentTemplateId { get; set; }
        public byte Civilian { get; set; }
        public string AIName { get; set; }
        public string ScriptName { get; set; }
    }
}
