//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbscript_random_templates
    {
        public long id { get; set; }
        public long type { get; set; }
        public int target_id { get; set; }
        public int chance { get; set; }
        public string comments { get; set; }
    }
}
