//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_event_mail
    {
        public short @event { get; set; }
        public decimal raceMask { get; set; }
        public decimal quest { get; set; }
        public decimal mailTemplateId { get; set; }
        public decimal senderEntry { get; set; }
    }
}
