//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class instance_dungeon_encounters
    {
        public long Id { get; set; }
        public long MapId { get; set; }
        public long Difficulty { get; set; }
        public long EncounterData { get; set; }
        public long EncounterIndex { get; set; }
        public string EncounterName { get; set; }
        public string EncounterName2 { get; set; }
        public string EncounterName3 { get; set; }
        public string EncounterName4 { get; set; }
        public string EncounterName5 { get; set; }
        public string EncounterName6 { get; set; }
        public string EncounterName7 { get; set; }
        public string EncounterName8 { get; set; }
        public string EncounterName9 { get; set; }
        public string EncounterName10 { get; set; }
        public string EncounterName11 { get; set; }
        public string EncounterName12 { get; set; }
        public string EncounterName13 { get; set; }
        public string EncounterName14 { get; set; }
        public string EncounterName15 { get; set; }
        public string EncounterName16 { get; set; }
        public long NameLangFlags { get; set; }
        public long SpellIconID { get; set; }
    }
}
