//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_loot_template
    {
        public decimal entry { get; set; }
        public decimal item { get; set; }
        public float ChanceOrQuestChance { get; set; }
        public byte groupid { get; set; }
        public decimal mincountOrRef { get; set; }
        public byte maxcount { get; set; }
        public decimal condition_id { get; set; }
        public string comments { get; set; }
    }
}
