//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class petcreateinfo_spell
    {
        public decimal entry { get; set; }
        public decimal Spell1 { get; set; }
        public decimal Spell2 { get; set; }
        public decimal Spell3 { get; set; }
        public decimal Spell4 { get; set; }
    }
}
