//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class questgiver_greeting
    {
        public long Entry { get; set; }
        public long Type { get; set; }
        public string Text { get; set; }
        public long EmoteId { get; set; }
        public long EmoteDelay { get; set; }
    }
}
