//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class script_waypoint
    {
        public decimal entry { get; set; }
        public long pathId { get; set; }
        public decimal pointid { get; set; }
        public string position_x { get; set; }
        public string position_y { get; set; }
        public string position_z { get; set; }
        public float orientation { get; set; }
        public long waittime { get; set; }
        public decimal script_id { get; set; }
        public string comment { get; set; }
    }
}
