//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class spell_chain
    {
        public decimal spell_id { get; set; }
        public decimal prev_spell { get; set; }
        public decimal first_spell { get; set; }
        public short rank { get; set; }
        public decimal req_spell { get; set; }
    }
}
