//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWDB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class achievement_reward
    {
        public decimal entry { get; set; }
        public short gender { get; set; }
        public decimal title_A { get; set; }
        public decimal title_H { get; set; }
        public decimal item { get; set; }
        public decimal sender { get; set; }
        public string subject { get; set; }
        public string text { get; set; }
    }
}
