//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWDB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class condition
    {
        public decimal condition_entry { get; set; }
        public short type { get; set; }
        public decimal value1 { get; set; }
        public decimal value2 { get; set; }
        public string comments { get; set; }
    }
}
