//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWDB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_model_info
    {
        public decimal modelid { get; set; }
        public float bounding_radius { get; set; }
        public float combat_reach { get; set; }
        public float SpeedWalk { get; set; }
        public float SpeedRun { get; set; }
        public byte gender { get; set; }
        public decimal modelid_other_gender { get; set; }
        public decimal modelid_other_team { get; set; }
    }
}
