//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWDB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_template_spells
    {
        public decimal entry { get; set; }
        public decimal spell1 { get; set; }
        public decimal spell2 { get; set; }
        public decimal spell3 { get; set; }
        public decimal spell4 { get; set; }
        public decimal spell5 { get; set; }
        public decimal spell6 { get; set; }
        public decimal spell7 { get; set; }
        public decimal spell8 { get; set; }
    }
}
