//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWDB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_template_classlevelstats_exp0
    {
        public short Level { get; set; }
        public short Class { get; set; }
        public decimal BaseHp { get; set; }
        public decimal BaseMana { get; set; }
        public decimal BaseArmor { get; set; }
        public float BaseDamage { get; set; }
        public float BaseMeleeDamage { get; set; }
        public float BaseRangedDamage { get; set; }
        public Nullable<float> CalculatedMeleeDiffPercent { get; set; }
        public float CalculatedMinMeleeDmg { get; set; }
        public float CalculatedMaxMeleeDmg { get; set; }
        public float FactoredSniffedMinMeleeDmg { get; set; }
        public float FactoredSniffedMaxMeleeDmg { get; set; }
        public Nullable<float> CalculatedRangedDiffPercent { get; set; }
        public float CalculatedMinRangedDmg { get; set; }
        public float CalculatedMaxRangedDmg { get; set; }
        public float FactoredSniffedMinRangedDmg { get; set; }
        public float FactoredSniffedMaxRangedDmg { get; set; }
        public decimal BaseMeleeAP { get; set; }
        public float MeleeAPModifier { get; set; }
        public decimal BaseRangedAP { get; set; }
        public decimal STR { get; set; }
        public decimal AGI { get; set; }
        public decimal STA { get; set; }
        public decimal INT { get; set; }
        public decimal SPI { get; set; }
        public string comments { get; set; }
    }
}
