//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWDB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class creature_model_race
    {
        public decimal modelid { get; set; }
        public decimal racemask { get; set; }
        public decimal creature_entry { get; set; }
        public decimal modelid_racial { get; set; }
    }
}
