//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWDB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_event
    {
        public decimal entry { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public long occurence { get; set; }
        public long length { get; set; }
        public decimal holiday { get; set; }
        public decimal linkedTo { get; set; }
        public string description { get; set; }
    }
}
