//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWDB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_event_creature_data
    {
        public long guid { get; set; }
        public decimal entry_id { get; set; }
        public decimal modelid { get; set; }
        public decimal equipment_id { get; set; }
        public decimal spell_start { get; set; }
        public decimal spell_end { get; set; }
        public int @event { get; set; }
    }
}
