//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWDB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gossip_menu
    {
        public int entry { get; set; }
        public decimal text_id { get; set; }
        public decimal script_id { get; set; }
        public decimal condition_id { get; set; }
    }
}
