//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWDB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_template
    {
        public decimal entry { get; set; }
        public byte @class { get; set; }
        public byte subclass { get; set; }
        public string name { get; set; }
        public decimal displayid { get; set; }
        public byte Quality { get; set; }
        public long Flags { get; set; }
        public byte BuyCount { get; set; }
        public long BuyPrice { get; set; }
        public long SellPrice { get; set; }
        public byte InventoryType { get; set; }
        public decimal AllowableClass { get; set; }
        public decimal AllowableRace { get; set; }
        public byte ItemLevel { get; set; }
        public byte RequiredLevel { get; set; }
        public int RequiredSkill { get; set; }
        public int RequiredSkillRank { get; set; }
        public decimal requiredspell { get; set; }
        public decimal requiredhonorrank { get; set; }
        public decimal RequiredCityRank { get; set; }
        public int RequiredReputationFaction { get; set; }
        public int RequiredReputationRank { get; set; }
        public int maxcount { get; set; }
        public int stackable { get; set; }
        public byte ContainerSlots { get; set; }
        public byte stat_type1 { get; set; }
        public short stat_value1 { get; set; }
        public byte stat_type2 { get; set; }
        public short stat_value2 { get; set; }
        public byte stat_type3 { get; set; }
        public short stat_value3 { get; set; }
        public byte stat_type4 { get; set; }
        public short stat_value4 { get; set; }
        public byte stat_type5 { get; set; }
        public short stat_value5 { get; set; }
        public byte stat_type6 { get; set; }
        public short stat_value6 { get; set; }
        public byte stat_type7 { get; set; }
        public short stat_value7 { get; set; }
        public byte stat_type8 { get; set; }
        public short stat_value8 { get; set; }
        public byte stat_type9 { get; set; }
        public short stat_value9 { get; set; }
        public byte stat_type10 { get; set; }
        public short stat_value10 { get; set; }
        public float dmg_min1 { get; set; }
        public float dmg_max1 { get; set; }
        public byte dmg_type1 { get; set; }
        public float dmg_min2 { get; set; }
        public float dmg_max2 { get; set; }
        public byte dmg_type2 { get; set; }
        public float dmg_min3 { get; set; }
        public float dmg_max3 { get; set; }
        public byte dmg_type3 { get; set; }
        public float dmg_min4 { get; set; }
        public float dmg_max4 { get; set; }
        public byte dmg_type4 { get; set; }
        public float dmg_min5 { get; set; }
        public float dmg_max5 { get; set; }
        public byte dmg_type5 { get; set; }
        public int armor { get; set; }
        public byte holy_res { get; set; }
        public byte fire_res { get; set; }
        public byte nature_res { get; set; }
        public byte frost_res { get; set; }
        public byte shadow_res { get; set; }
        public byte arcane_res { get; set; }
        public int delay { get; set; }
        public byte ammo_type { get; set; }
        public float RangedModRange { get; set; }
        public decimal spellid_1 { get; set; }
        public byte spelltrigger_1 { get; set; }
        public short spellcharges_1 { get; set; }
        public float spellppmRate_1 { get; set; }
        public int spellcooldown_1 { get; set; }
        public int spellcategory_1 { get; set; }
        public int spellcategorycooldown_1 { get; set; }
        public decimal spellid_2 { get; set; }
        public byte spelltrigger_2 { get; set; }
        public short spellcharges_2 { get; set; }
        public float spellppmRate_2 { get; set; }
        public int spellcooldown_2 { get; set; }
        public int spellcategory_2 { get; set; }
        public int spellcategorycooldown_2 { get; set; }
        public decimal spellid_3 { get; set; }
        public byte spelltrigger_3 { get; set; }
        public short spellcharges_3 { get; set; }
        public float spellppmRate_3 { get; set; }
        public int spellcooldown_3 { get; set; }
        public int spellcategory_3 { get; set; }
        public int spellcategorycooldown_3 { get; set; }
        public decimal spellid_4 { get; set; }
        public byte spelltrigger_4 { get; set; }
        public short spellcharges_4 { get; set; }
        public float spellppmRate_4 { get; set; }
        public int spellcooldown_4 { get; set; }
        public int spellcategory_4 { get; set; }
        public int spellcategorycooldown_4 { get; set; }
        public decimal spellid_5 { get; set; }
        public byte spelltrigger_5 { get; set; }
        public short spellcharges_5 { get; set; }
        public float spellppmRate_5 { get; set; }
        public int spellcooldown_5 { get; set; }
        public int spellcategory_5 { get; set; }
        public int spellcategorycooldown_5 { get; set; }
        public byte bonding { get; set; }
        public string description { get; set; }
        public decimal PageText { get; set; }
        public byte LanguageID { get; set; }
        public byte PageMaterial { get; set; }
        public decimal startquest { get; set; }
        public decimal lockid { get; set; }
        public short Material { get; set; }
        public byte sheath { get; set; }
        public decimal RandomProperty { get; set; }
        public decimal block { get; set; }
        public decimal itemset { get; set; }
        public int MaxDurability { get; set; }
        public decimal area { get; set; }
        public short Map { get; set; }
        public decimal BagFamily { get; set; }
        public string ScriptName { get; set; }
        public decimal DisenchantID { get; set; }
        public byte FoodType { get; set; }
        public long minMoneyLoot { get; set; }
        public long maxMoneyLoot { get; set; }
        public long Duration { get; set; }
        public byte ExtraFlags { get; set; }
    }
}
