//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWDB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pool_creature_template
    {
        public long id { get; set; }
        public decimal pool_entry { get; set; }
        public float chance { get; set; }
        public string description { get; set; }
    }
}
