//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWDB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_poi
    {
        public decimal questId { get; set; }
        public byte poiId { get; set; }
        public int objIndex { get; set; }
        public long mapId { get; set; }
        public decimal mapAreaId { get; set; }
        public byte floorId { get; set; }
        public long unk3 { get; set; }
        public long unk4 { get; set; }
    }
}
