//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWDB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxi_shortcuts
    {
        public long pathid { get; set; }
        public long takeoff { get; set; }
        public long landing { get; set; }
        public string comments { get; set; }
    }
}
